### PR TITLE
feat: Report Bug button added

### PR DESCRIPTION
**Pull request by cheemney**
#20 
[fix(manifest): Updated manifest to include broader website support](https://github.com/alicangunduz/knock-knock-follow-me/commit/472983ce670c69114b972215cd158b2c4c4c4fed)

new font added (more readable) and some styles changed 
[fix: typo](https://github.com/alicangunduz/knock-knock-follow-me/pull/21/commits/0192d0ef6902f04fe6e8f2e981fb18c1b8025850)

### CODE REVIEW

**Comment by alicangunduz** [comment]
@itsBLOK  Can we activate the language option in the plugin settings interface, like the token field report bug.

**Comment by itsBLOK** [comment]
i pushed that pr by mistake because it's WIP rn, i was thinking of having the browser's language pulled but it makes more sense to offer a choice

**Comment by alicangunduz** [comment]
@itsBLOK  should I close it or wait? Which one do you want? By the way, if you have any questions, I can definitely help you.

**Comment by itsBLOK** [comment]
you can merge commit and close it, other changes made re fine, only language support will be a bit delayed, i have other things going on at the moment and i will look at it when i have time

**Review by alicangunduz — APPROVED** [review]
💯

**Pull request merged**
